### ISSUE TITLE
Subject customization from command line

### ISSUE THREAD

**Issue by giosh94mhz** [nabeken/go-smtp-source#7]
Hi!

I see there is no possibility to change the subject from command line. I see in the original `smtp-source` there is the `-S` which can possibly be replicated.

Another cool feature for the subject is having a `%d` escape code to insert the test number. This way I can add a subject like `-S "Test #1 mail #%d` and have more feedback on the destination.

Sorry I don't provide a PR, but I have never programmed in Go.

**Comment by nabeken** [comment]
@giosh94mhz Hi, thank you for opening the issue! I liked the idea so I pushed #8. Please give it a try.

**Comment by giosh94mhz** [comment]
Great, thank you! 

I can now debug missing email and see the receive order.
![immagine](https://user-images.githubusercontent.com/5219975/38677818-a4fa2914-3e5f-11e8-8bf3-cbdae579e8f4.png)
